// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: protos/database-server/operations.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	QueryObject   string                 `protobuf:"bytes,2,opt,name=query_object,json=queryObject,proto3" json:"query_object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadQuery) Reset() {
	*x = ReadQuery{}
	mi := &file_protos_database_server_operations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadQuery) ProtoMessage() {}

func (x *ReadQuery) ProtoReflect() protoreflect.Message {
	mi := &file_protos_database_server_operations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadQuery.ProtoReflect.Descriptor instead.
func (*ReadQuery) Descriptor() ([]byte, []int) {
	return file_protos_database_server_operations_proto_rawDescGZIP(), []int{0}
}

func (x *ReadQuery) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *ReadQuery) GetQueryObject() string {
	if x != nil {
		return x.QueryObject
	}
	return ""
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataObject    string                 `protobuf:"bytes,1,opt,name=data_object,json=dataObject,proto3" json:"data_object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_protos_database_server_operations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_database_server_operations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_protos_database_server_operations_proto_rawDescGZIP(), []int{1}
}

func (x *ReadResponse) GetDataObject() string {
	if x != nil {
		return x.DataObject
	}
	return ""
}

type WriteQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	WriteObject   string                 `protobuf:"bytes,2,opt,name=write_object,json=writeObject,proto3" json:"write_object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteQuery) Reset() {
	*x = WriteQuery{}
	mi := &file_protos_database_server_operations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteQuery) ProtoMessage() {}

func (x *WriteQuery) ProtoReflect() protoreflect.Message {
	mi := &file_protos_database_server_operations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteQuery.ProtoReflect.Descriptor instead.
func (*WriteQuery) Descriptor() ([]byte, []int) {
	return file_protos_database_server_operations_proto_rawDescGZIP(), []int{2}
}

func (x *WriteQuery) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *WriteQuery) GetWriteObject() string {
	if x != nil {
		return x.WriteObject
	}
	return ""
}

type WriteResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WriteCompleted bool                   `protobuf:"varint,1,opt,name=write_completed,json=writeCompleted,proto3" json:"write_completed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_protos_database_server_operations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_database_server_operations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_protos_database_server_operations_proto_rawDescGZIP(), []int{3}
}

func (x *WriteResponse) GetWriteCompleted() bool {
	if x != nil {
		return x.WriteCompleted
	}
	return false
}

type UpdateQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadQuery     *ReadQuery             `protobuf:"bytes,1,opt,name=read_query,json=readQuery,proto3" json:"read_query,omitempty"`
	WriteQuery    *WriteQuery            `protobuf:"bytes,2,opt,name=write_query,json=writeQuery,proto3" json:"write_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuery) Reset() {
	*x = UpdateQuery{}
	mi := &file_protos_database_server_operations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuery) ProtoMessage() {}

func (x *UpdateQuery) ProtoReflect() protoreflect.Message {
	mi := &file_protos_database_server_operations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuery.ProtoReflect.Descriptor instead.
func (*UpdateQuery) Descriptor() ([]byte, []int) {
	return file_protos_database_server_operations_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateQuery) GetReadQuery() *ReadQuery {
	if x != nil {
		return x.ReadQuery
	}
	return nil
}

func (x *UpdateQuery) GetWriteQuery() *WriteQuery {
	if x != nil {
		return x.WriteQuery
	}
	return nil
}

var File_protos_database_server_operations_proto protoreflect.FileDescriptor

const file_protos_database_server_operations_proto_rawDesc = "" +
	"\n" +
	"'protos/database-server/operations.proto\x12\n" +
	"operations\"N\n" +
	"\tReadQuery\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12!\n" +
	"\fquery_object\x18\x02 \x01(\tR\vqueryObject\"/\n" +
	"\fReadResponse\x12\x1f\n" +
	"\vdata_object\x18\x01 \x01(\tR\n" +
	"dataObject\"O\n" +
	"\n" +
	"WriteQuery\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12!\n" +
	"\fwrite_object\x18\x02 \x01(\tR\vwriteObject\"8\n" +
	"\rWriteResponse\x12'\n" +
	"\x0fwrite_completed\x18\x01 \x01(\bR\x0ewriteCompleted\"|\n" +
	"\vUpdateQuery\x124\n" +
	"\n" +
	"read_query\x18\x01 \x01(\v2\x15.operations.ReadQueryR\treadQuery\x127\n" +
	"\vwrite_query\x18\x02 \x01(\v2\x16.operations.WriteQueryR\n" +
	"writeQuery2\xaa\x02\n" +
	"\x19DatabaseOperationsService\x12?\n" +
	"\n" +
	"GetRecords\x12\x15.operations.ReadQuery\x1a\x18.operations.ReadResponse\"\x00\x12B\n" +
	"\vWriteRecord\x12\x16.operations.WriteQuery\x1a\x19.operations.WriteResponse\"\x00\x12D\n" +
	"\fUpdateRecord\x12\x17.operations.UpdateQuery\x1a\x19.operations.WriteResponse\"\x00\x12B\n" +
	"\fDeleteRecord\x12\x15.operations.ReadQuery\x1a\x19.operations.WriteResponse\"\x00B\n" +
	"Z\b./serverb\x06proto3"

var (
	file_protos_database_server_operations_proto_rawDescOnce sync.Once
	file_protos_database_server_operations_proto_rawDescData []byte
)

func file_protos_database_server_operations_proto_rawDescGZIP() []byte {
	file_protos_database_server_operations_proto_rawDescOnce.Do(func() {
		file_protos_database_server_operations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_database_server_operations_proto_rawDesc), len(file_protos_database_server_operations_proto_rawDesc)))
	})
	return file_protos_database_server_operations_proto_rawDescData
}

var file_protos_database_server_operations_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_database_server_operations_proto_goTypes = []any{
	(*ReadQuery)(nil),     // 0: operations.ReadQuery
	(*ReadResponse)(nil),  // 1: operations.ReadResponse
	(*WriteQuery)(nil),    // 2: operations.WriteQuery
	(*WriteResponse)(nil), // 3: operations.WriteResponse
	(*UpdateQuery)(nil),   // 4: operations.UpdateQuery
}
var file_protos_database_server_operations_proto_depIdxs = []int32{
	0, // 0: operations.UpdateQuery.read_query:type_name -> operations.ReadQuery
	2, // 1: operations.UpdateQuery.write_query:type_name -> operations.WriteQuery
	0, // 2: operations.DatabaseOperationsService.GetRecords:input_type -> operations.ReadQuery
	2, // 3: operations.DatabaseOperationsService.WriteRecord:input_type -> operations.WriteQuery
	4, // 4: operations.DatabaseOperationsService.UpdateRecord:input_type -> operations.UpdateQuery
	0, // 5: operations.DatabaseOperationsService.DeleteRecord:input_type -> operations.ReadQuery
	1, // 6: operations.DatabaseOperationsService.GetRecords:output_type -> operations.ReadResponse
	3, // 7: operations.DatabaseOperationsService.WriteRecord:output_type -> operations.WriteResponse
	3, // 8: operations.DatabaseOperationsService.UpdateRecord:output_type -> operations.WriteResponse
	3, // 9: operations.DatabaseOperationsService.DeleteRecord:output_type -> operations.WriteResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_database_server_operations_proto_init() }
func file_protos_database_server_operations_proto_init() {
	if File_protos_database_server_operations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_database_server_operations_proto_rawDesc), len(file_protos_database_server_operations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_database_server_operations_proto_goTypes,
		DependencyIndexes: file_protos_database_server_operations_proto_depIdxs,
		MessageInfos:      file_protos_database_server_operations_proto_msgTypes,
	}.Build()
	File_protos_database_server_operations_proto = out.File
	file_protos_database_server_operations_proto_goTypes = nil
	file_protos_database_server_operations_proto_depIdxs = nil
}
